[package]
name = "rsfunceble"
version = "0.0.1"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
trust-dns-resolver = "0.20"
whois-rust = "1.6.0"
clap = { version = "4.0", features = ["derive"] }
